export const mockArtists = [
  {
    id: "1",
    parentId: null,
    name: "Vincent van Gogh",
    termId: "term-1",
    contributorId: "contrib-1",
    fullName: "Vincent Willem van Gogh",
    type: "painter",
    nationalityCode: "NL",
    description: "Dutch post-impressionist painter",
  },
  {
    id: "2",
    parentId: null,
    name: "Pablo Picasso",
    termId: "term-2",
    contributorId: "contrib-2",
    fullName: "Pablo Diego José Francisco de Paula Juan Nepomuceno María de los Remedios Cipriano de la Santísima Trinidad Ruiz y Picasso",
    type: "painter",
    nationalityCode: "ES",
    description: "Spanish painter, sculptor, printmaker, ceramicist and theatre designer",
  },
  {
    id: "3",
    parentId: null,
    name: "Auguste Rodin",
    termId: "term-3",
    contributorId: "contrib-3",
    fullName: "François-Auguste-René Rodin",
    type: "sculptor",
    nationalityCode: "FR",
    description: "French sculptor, generally considered the founder of modern sculpture",
  },
  {
    id: "4",
    parentId: null,
    name: "Leonardo da Vinci",
    termId: "term-4",
    contributorId: "contrib-4",
    fullName: "Leonardo di ser Piero da Vinci",
    type: "painter",
    nationalityCode: "IT",
    description: "Italian polymath of the High Renaissance",
  },
  {
    id: "5",
    parentId: null,
    name: "Frida Kahlo",
    termId: "term-5",
    contributorId: "contrib-5",
    fullName: "Magdalena Carmen Frida Kahlo y Calderón",
    type: "painter",
    nationalityCode: "MX",
    description: "Mexican painter known for her many portraits, self-portraits, and works inspired by the nature and artifacts of Mexico",
  },
];